declare module "ascii-table";
declare module "get-image-colors";
declare module "is-hex-color";
declare module "weather-js";
declare module "minecraft_head";
declare module "crafatar";
declare module "image-moderation";
declare module "discord.js-akinator";
declare module "either-wyr";
